# Generated by Django 4.2.3 on 2023-07-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='transaction_history',
            field=models.TextField(default='[]'),
        ),
    ]
