# Generated by Django 4.2.3 on 2023-08-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_reports',
            field=models.IntegerField(default=0),
        ),
    ]
