# Generated by Django 4.2.3 on 2023-07-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_remove_recipe_ingredients_delete_ingredients_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
