# Generated by Django 4.2.3 on 2023-07-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_report_recipe_revenue_recipe_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
