# Generated by Django 4.2.3 on 2023-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_recipe_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
