# Generated by Django 4.2.3 on 2023-07-28 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_recipe_revenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
