# Generated by Django 4.2.3 on 2023-08-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_comment_user_id_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
