# Generated by Django 4.2.3 on 2023-08-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_remove_recipe_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
