services:
    nginx:
        restart: always
        build:
          context: ./nginx/
          dockerfile: Dockerfile.nginx
        ports:
          - "80:80"
        depends_on:
          - backend
        volumes:
          - static_volume:/vol/static
          - media_volume:/vol/media
    backend:
        restart: always
        build: .
        entrypoint: /app/server-entrypoint.sh
        volumes:
            - static_volume:/vol/app
            - db_data:/app/db.sqlite3
            - media_volume:/vol/media
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        depends_on:
            - redis

    worker:
        restart: always
        build: . 
        entrypoint: /app/worker-entrypoint.sh
        volumes:
            - static_volume:/app/app
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
        depends_on:
            - backend
            - redis
    beat:
        restart: always
        build: . 
        entrypoint: /app/beat-entrypoint.sh
        volumes:
            - static_volume:/app/app
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
        depends_on:
            - backend
            - redis
    redis:
        restart: always
        image: redis:7.0.5-alpine 
        expose:
            - 6379
    
    
    
    
volumes:
    static_volume:
    media_volume:
    db_data:

    