# Generated by Django 4.2.3 on 2023-07-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
