FROM nginx:1.23.0-alpine


COPY ./nginx/* /etc/nginx/
COPY ./run.sh /run.sh

ENV APP_HOST =app
ENV APP_PORT=9000

RUN apk add --no-cache openssl bash
RUN chmod +x /run.sh

USER root

RUN mkdir -p /vol/app/static && \
    chmod 755 /vol/app/static && \ 
    mkdir -p /vol/app/media && \
    chmod 755 /vol/app/media

VOLUME /vol/app/static
VOLUME /vol/app/media
VOLUME /vol/www

CMD [ "/run.sh" ]


# CMD [ "/bin/bash", "-c", "nginx -g 'daemon off;'" ]